version: '3'
services:
  glassfish:
    build: .
    ports:
      - 8080:8080
      - 4848:4848
    links:
      - mysql
      
  mysql:
    build: ./DB
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ehr 
      MYSQL_USER: ehr
      MYSQL_PASSWORD: ehr
      MYSQL_ROOT_HOST: '%'

