version: '3'
services:
  glassfish:
    build: .
    ports:
      - 8080:30000
      - 4848:31000
    links:
      - mysql
      
  mysql:
    build: ./DB
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ehr 
      MYSQL_USER: ehr
      MYSQL_PASSWORD: ehr
      MYSQL_ROOT_HOST: '%'

